import type { Vehicle } from '../../public/index';

// Used for POST /api/vehicles (id is auto-generated by the backend)
export type VehiclePayload = Omit<Vehicle, 'id'>;

// Used by ms-operations endpoints — wraps a Vehicle
export type VehicleRequest = {
  vehicle: Vehicle;
};

// Returned by all ms-operations endpoints
export type ReservationResponse = {
  message: string;
  vehicle: Vehicle;
};
